### ISSUE TITLE
Не понял как исправить эти две ошибки. Не проходит сборка билда 

### ISSUE THREAD

**Issue by stlkralexdemo** [stlkralexdemo/UlmartHW#2]
[ERROR] ru.itpark.comparator.ItemsNameAscComparator implements Comparator but not Serializable [ru.itpark.comparator.ItemsNameAscComparator] At ItemsNameAscComparator.java:[lines 7-12] SE_COMPARATOR_SHOULD_BE_SERIALIZABLE
[ERROR] ru.itpark.comparator.ItemsPriceAscComparator implements Comparator but not Serializable [ru.itpark.comparator.ItemsPriceAscComparator] At ItemsPriceAscComparator.java:[lines 7-12] SE_COMPARATOR_SHOULD_BE_SERIALIZABLE

**Comment by coursar** [comment]
Добавьте `implements Serializable`
